# Keep mode_modules between jobs (results in lower build times)
cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

stages:
  - install
  - verify
  - build
  - docker-build
  - deploy

image: trion/ng-cli-karma:latest

Install dependencies:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull-push
  stage: install
  script: npm i
  tags:
    - dualis
    - docker

Verify lint:
  stage: verify
  script: npm run lint
  tags:
    - dualis
    - docker

Verify karma-test:
  stage: verify
  script: ng test --code-coverage --progress false --watch false
  artifacts:
    paths:
      - coverage/
  tags:
    - dualis
    - docker

Build release:
  stage: build
  script:
    - npm run build-prod
  only:
    - master
    - tags
  artifacts:
    paths:
      - dist/*
  tags:
    - dualis
    - docker

Build dev:
  stage: build
  script:
    - npm run build-dev
  except:
    - master
    - tags
  artifacts:
    paths:
      - dist/*
  tags:
    - dualis
    - docker

Build docker release:
  # Official docker image.
  image: docker:latest
  stage: docker-build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY/$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY/$CI_REGISTRY_IMAGE"
  only:
    - tags
  tags:
    - docker
    - dualis

Build docker dev:
  # Official docker image.
  image: docker:latest
  stage: docker-build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
    - tags
  tags:
    - docker
    - dualis

Deploy release:
  stage: deploy
  cache: {}  # no cache required for deployment
  script:
    - cd /opt/services/dualis
    - docker-compose pull $COMPOSE_SERVICE_NAME
    - docker-compose restart $COMPOSE_SERVICE_NAME
  only:
    - tags # only deploy a real release
  tags:
    - dualis
    - shell

pages:
  stage: deploy
  cache:
    # inherit all global cache settings
    <<: *global_cache
    key: pages
    paths:
      - public
    policy: pull-push
  dependencies:
    - Verify karma-test
  script:
    - mv coverage/dualis-rework/* coverage/
    - mkdir -p public/$CI_COMMIT_REF_SLUG
    - cp -a coverage/* public/$CI_COMMIT_REF_SLUG
    - cd public
    - sh ../gitlab-pages/generate-dir-index.sh
    - cp ../gitlab-pages/styles.css .
  artifacts:
    name: "$CI_PIPELINE_ID"
    paths:
      - public
  tags:
    - dualis
