# Keep mode_modules between jobs (results in lower build times)
cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

stages:
  - install
  - verify
  - build
  - deploy

image: trion/ng-cli-karma:latest

Install dependencies:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull-push
  stage: install
  script: npm i
  tags:
    - dualis
    - docker

Verify lint:
  stage: verify
  script: npm run lint
  tags:
    - dualis
    - docker

Verify karma-test:
  stage: verify
  script: ng test --code-coverage --progress false --watch false
  artifacts:
    paths:
      - coverage/
  tags:
    - dualis
    - docker

Build release:
  stage: build
  script:
    - npm run build-prod
  only:
    - master
    - tags
  artifacts:
    paths:
      - dist/*
  tags:
    - dualis
    - docker

Build dev:
  stage: build
  script:
    - npm run build-dev
  except:
    - master
    - tags
  artifacts:
    paths:
      - dist/*
  tags:
    - dualis
    - docker

Deploy release:
  stage: deploy
  cache: {}  # no cache required for deployment
  script:
    - rm /opt/services/dualis/website-angular-build/prod/* || true
    - cp dist/dualis-rework/* /opt/services/dualis/website-angular-build/prod/
  only:
    - tags # only deploy a real release
  tags:
    - dualis
    - shell

Deploy dev:
  stage: deploy
  cache: {}  # no cache required for deployment
  script:
    - rm /opt/services/dualis/website-angular-build/dev/* || true
    - cp dist/dualis-rework/*  /opt/services/dualis/website-angular-build/dev/
  except:
    - master
    - tags
  tags:
    - dualis
    - shell

pages:
  stage: deploy
  cache:
    # inherit all global cache settings
    <<: *global_cache
    key: pages
    paths:
      - public
    policy: pull-push
  dependencies:
    - Verify karma-test
  script:
    - apt update
    - apt install tree -y
    - mv coverage/dualis-rework/* coverage/
    - mkdir -p public/$CI_COMMIT_REF_SLUG
    - cp -a coverage/* public/$CI_COMMIT_REF_SLUG
    - cd public
    - tree -H '.' -L 1 --noreport --charset utf-8 > index.html
  artifacts:
    name: "$CI_PIPELINE_ID"
    paths:
      - public
  tags:
    - dualis
  when: always
